# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_check_in', models.CharField(max_length=25)),
                ('date_check_out', models.CharField(max_length=25)),
                ('guest_name', models.CharField(max_length=25)),
                ('property_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
