# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproperty',
            name='date_check_in',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bookproperty',
            name='date_check_out',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
