# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_property', '0002_auto_20170720_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookproperty',
            new_name='Booking',
        ),
    ]
