# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_check_in', models.DateField(default=datetime.date.today)),
                ('date_check_out', models.DateField(default=datetime.date.today)),
                ('guest_name', models.CharField(max_length=25)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
