# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=150, unique=True)),
                ('number_of_bedrooms', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Client')),
            ],
        ),
    ]
