# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Address',
            field=models.CharField(max_length=150),
        ),
    ]
